version: '2'
services:
  influxdb:
    image: influxdb:1.2.2
    ports:
      - 8086:8086
      - 8083:8083
  chronograf:
    image: chronograf:0.13.0
    ports:
      - 10000:10000
    links:
      - influxdb:influxdb
    volumes:
      - ./chronograf:/var/lib/chronograf
